name: Daily NHL Bot Run

on:
  schedule:
    # Runs every day at 08:00 UTC.
    # This will be 11:00 AM in Finland during EEST (UTC+3) and 10:00 AM during EET (UTC+2).
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI for testing

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Ingest Script for Today's Date
        # The 'ingest' script needs today's date to fetch games that finished by now.
        # 'date +%Y-%m-%d' gets the current date in YYYY-MM-DD format on Linux.
        run: npm run ingest -- --date $(date +%Y-%m-%d)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Post Script for Yesterday's Games
        # The 'post:nightly' script defaults to yesterday's date, which is usually what you want for a "nightly" post.
        run: npm run post:nightly
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_ENABLE: '1' # Set to '1' to enable actual tweeting
